// This file was generated by counterfeiter
package cfmysqlfakes

import (
	"sync"

	"code.cloudfoundry.org/cli/plugin"
	"github.com/andreasf/cf-mysql-plugin/cfmysql"
)

type FakeCfClient struct {
	GetMysqlServicesStub        func(cliConnection plugin.CliConnection) ([]cfmysql.MysqlService, error)
	getMysqlServicesMutex       sync.RWMutex
	getMysqlServicesArgsForCall []struct {
		cliConnection plugin.CliConnection
	}
	getMysqlServicesReturns struct {
		result1 []cfmysql.MysqlService
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCfClient) GetMysqlServices(cliConnection plugin.CliConnection) ([]cfmysql.MysqlService, error) {
	fake.getMysqlServicesMutex.Lock()
	fake.getMysqlServicesArgsForCall = append(fake.getMysqlServicesArgsForCall, struct {
		cliConnection plugin.CliConnection
	}{cliConnection})
	fake.recordInvocation("GetMysqlServices", []interface{}{cliConnection})
	fake.getMysqlServicesMutex.Unlock()
	if fake.GetMysqlServicesStub != nil {
		return fake.GetMysqlServicesStub(cliConnection)
	} else {
		return fake.getMysqlServicesReturns.result1, fake.getMysqlServicesReturns.result2
	}
}

func (fake *FakeCfClient) GetMysqlServicesCallCount() int {
	fake.getMysqlServicesMutex.RLock()
	defer fake.getMysqlServicesMutex.RUnlock()
	return len(fake.getMysqlServicesArgsForCall)
}

func (fake *FakeCfClient) GetMysqlServicesArgsForCall(i int) plugin.CliConnection {
	fake.getMysqlServicesMutex.RLock()
	defer fake.getMysqlServicesMutex.RUnlock()
	return fake.getMysqlServicesArgsForCall[i].cliConnection
}

func (fake *FakeCfClient) GetMysqlServicesReturns(result1 []cfmysql.MysqlService, result2 error) {
	fake.GetMysqlServicesStub = nil
	fake.getMysqlServicesReturns = struct {
		result1 []cfmysql.MysqlService
		result2 error
	}{result1, result2}
}

func (fake *FakeCfClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMysqlServicesMutex.RLock()
	defer fake.getMysqlServicesMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCfClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cfmysql.CfClient = new(FakeCfClient)
