// This file was generated by counterfeiter
package cfmysqlfakes

import (
	"sync"

	"code.cloudfoundry.org/cli/plugin"

	"github.com/andreasf/cf-mysql-plugin/cfmysql"
	modelscfmysql "github.com/andreasf/cf-mysql-plugin/cfmysql/models"

	"code.cloudfoundry.org/cli/plugin/models"
)

type FakeApiClient struct {
	GetServiceBindingsStub        func(cliConnection plugin.CliConnection) ([]modelscfmysql.ServiceBinding, error)
	getServiceBindingsMutex       sync.RWMutex
	getServiceBindingsArgsForCall []struct {
		cliConnection plugin.CliConnection
	}
	getServiceBindingsReturns struct {
		result1 []modelscfmysql.ServiceBinding
		result2 error
	}
	GetServiceInstancesStub        func(cliConnection plugin.CliConnection) ([]modelscfmysql.ServiceInstance, error)
	getServiceInstancesMutex       sync.RWMutex
	getServiceInstancesArgsForCall []struct {
		cliConnection plugin.CliConnection
	}
	getServiceInstancesReturns struct {
		result1 []modelscfmysql.ServiceInstance
		result2 error
	}
	GetStartedAppsStub        func(cliConnection plugin.CliConnection) ([]plugin_models.GetAppsModel, error)
	getStartedAppsMutex       sync.RWMutex
	getStartedAppsArgsForCall []struct {
		cliConnection plugin.CliConnection
	}
	getStartedAppsReturns struct {
		result1 []plugin_models.GetAppsModel
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeApiClient) GetServiceBindings(cliConnection plugin.CliConnection) ([]modelscfmysql.ServiceBinding, error) {
	fake.getServiceBindingsMutex.Lock()
	fake.getServiceBindingsArgsForCall = append(fake.getServiceBindingsArgsForCall, struct {
		cliConnection plugin.CliConnection
	}{cliConnection})
	fake.recordInvocation("GetServiceBindings", []interface{}{cliConnection})
	fake.getServiceBindingsMutex.Unlock()
	if fake.GetServiceBindingsStub != nil {
		return fake.GetServiceBindingsStub(cliConnection)
	} else {
		return fake.getServiceBindingsReturns.result1, fake.getServiceBindingsReturns.result2
	}
}

func (fake *FakeApiClient) GetServiceBindingsCallCount() int {
	fake.getServiceBindingsMutex.RLock()
	defer fake.getServiceBindingsMutex.RUnlock()
	return len(fake.getServiceBindingsArgsForCall)
}

func (fake *FakeApiClient) GetServiceBindingsArgsForCall(i int) plugin.CliConnection {
	fake.getServiceBindingsMutex.RLock()
	defer fake.getServiceBindingsMutex.RUnlock()
	return fake.getServiceBindingsArgsForCall[i].cliConnection
}

func (fake *FakeApiClient) GetServiceBindingsReturns(result1 []modelscfmysql.ServiceBinding, result2 error) {
	fake.GetServiceBindingsStub = nil
	fake.getServiceBindingsReturns = struct {
		result1 []modelscfmysql.ServiceBinding
		result2 error
	}{result1, result2}
}

func (fake *FakeApiClient) GetServiceInstances(cliConnection plugin.CliConnection) ([]modelscfmysql.ServiceInstance, error) {
	fake.getServiceInstancesMutex.Lock()
	fake.getServiceInstancesArgsForCall = append(fake.getServiceInstancesArgsForCall, struct {
		cliConnection plugin.CliConnection
	}{cliConnection})
	fake.recordInvocation("GetServiceInstances", []interface{}{cliConnection})
	fake.getServiceInstancesMutex.Unlock()
	if fake.GetServiceInstancesStub != nil {
		return fake.GetServiceInstancesStub(cliConnection)
	} else {
		return fake.getServiceInstancesReturns.result1, fake.getServiceInstancesReturns.result2
	}
}

func (fake *FakeApiClient) GetServiceInstancesCallCount() int {
	fake.getServiceInstancesMutex.RLock()
	defer fake.getServiceInstancesMutex.RUnlock()
	return len(fake.getServiceInstancesArgsForCall)
}

func (fake *FakeApiClient) GetServiceInstancesArgsForCall(i int) plugin.CliConnection {
	fake.getServiceInstancesMutex.RLock()
	defer fake.getServiceInstancesMutex.RUnlock()
	return fake.getServiceInstancesArgsForCall[i].cliConnection
}

func (fake *FakeApiClient) GetServiceInstancesReturns(result1 []modelscfmysql.ServiceInstance, result2 error) {
	fake.GetServiceInstancesStub = nil
	fake.getServiceInstancesReturns = struct {
		result1 []modelscfmysql.ServiceInstance
		result2 error
	}{result1, result2}
}

func (fake *FakeApiClient) GetStartedApps(cliConnection plugin.CliConnection) ([]plugin_models.GetAppsModel, error) {
	fake.getStartedAppsMutex.Lock()
	fake.getStartedAppsArgsForCall = append(fake.getStartedAppsArgsForCall, struct {
		cliConnection plugin.CliConnection
	}{cliConnection})
	fake.recordInvocation("GetStartedApps", []interface{}{cliConnection})
	fake.getStartedAppsMutex.Unlock()
	if fake.GetStartedAppsStub != nil {
		return fake.GetStartedAppsStub(cliConnection)
	} else {
		return fake.getStartedAppsReturns.result1, fake.getStartedAppsReturns.result2
	}
}

func (fake *FakeApiClient) GetStartedAppsCallCount() int {
	fake.getStartedAppsMutex.RLock()
	defer fake.getStartedAppsMutex.RUnlock()
	return len(fake.getStartedAppsArgsForCall)
}

func (fake *FakeApiClient) GetStartedAppsArgsForCall(i int) plugin.CliConnection {
	fake.getStartedAppsMutex.RLock()
	defer fake.getStartedAppsMutex.RUnlock()
	return fake.getStartedAppsArgsForCall[i].cliConnection
}

func (fake *FakeApiClient) GetStartedAppsReturns(result1 []plugin_models.GetAppsModel, result2 error) {
	fake.GetStartedAppsStub = nil
	fake.getStartedAppsReturns = struct {
		result1 []plugin_models.GetAppsModel
		result2 error
	}{result1, result2}
}

func (fake *FakeApiClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getServiceBindingsMutex.RLock()
	defer fake.getServiceBindingsMutex.RUnlock()
	fake.getServiceInstancesMutex.RLock()
	defer fake.getServiceInstancesMutex.RUnlock()
	fake.getStartedAppsMutex.RLock()
	defer fake.getStartedAppsMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeApiClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cfmysql.ApiClient = new(FakeApiClient)
